services:
  # Serviço do Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço do pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - db

  # Backend Spring Boot
  app:
    build: .
    container_name: ai-dev-stack-backend
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Banco de dados
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

      # JWT
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}

      # DataInitializer
      - DATA_INIT_ADMIN_EMAIL=${ADMIN_EMAIL}
      - DATA_INIT_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DATA_INIT_USER_EMAIL=${USER_EMAIL}
      - DATA_INIT_USER_PASSWORD=${USER_PASSWORD}

volumes:
  pgdata: