services:
  # Serviço do Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=meu_banco
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Serviço do pgAdmin (Para você não precisar instalar nada no Windows)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8082:80"
    depends_on:
      - db

  # Seu Backend Spring Boot
  app:
    build: .
    container_name: ai-dev-stack-backend
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/meu_banco
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=senha
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  pgdata: