spring.application.name=AI_Dev_Stack
server.port=${PORT:8081}

# Banco de dados
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ai_dev_stack}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# Driver e Dialeto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Estrategia de Banco de Dados
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Swagger
springdoc.swagger-ui.path=/swagger-ui
springdoc.openapi.info.title=AI Dev Stack API
springdoc.openapi.info.version=1.0.0
springdoc.openapi.info.description=Backend MVP documentation for the AI Dev Stack

# JWT (Corrigido)
jwt.secret=${JWT_SECRET:c10a40e78895742da6db3c09b1efc406c577cb32b2f66f7f799bcb51003e2f7d}
jwt.expiration=${JWT_EXPIRATION:86400000}

# DataInitializer
data.init.admin.email=${DATA_INIT_ADMIN_EMAIL:admin@exemple.com}
data.init.admin.password=${DATA_INIT_ADMIN_PASSWORD:senhaAdmin}
data.init.user.email=${DATA_INIT_USER_EMAIL:dev@exemple.com}
data.init.user.password=${DATA_INIT_USER_PASSWORD:senhaDev}

spring.jackson.mapper.accept-case-insensitive-enums=true